### ISSUE TITLE
 Failed:  Hot Mocker file replacement failed!!

### ISSUE THREAD

**Issue by super918180** [jaywcjlove/webpack-api-mocker#10]

**Comment by jaywcjlove** [comment]
`./mocker.js` => `./mocker/index.js`

New version requires listening directory

@super918180

**Comment by SoyMeng** [comment]
应该跟这个是同一个问题，由于接口比较多，分包格式类似
```
/admin/index.js
/sys/index.js
...

```

热更新就不起作用了

**Comment by jaywcjlove** [comment]
```js
mocker/admin/index.js  
mocker/sys/index.js  
```

**Comment by jaywcjlove** [comment]
@SoyMeng 更新了个最新版本更新试试看，新版本需要放到一个目录中

**Comment by MEEllis** [comment]
"webpack-api-mocker": "^1.5.7" , 按照教程走也是出现 

![bf oq k9zz6igt tq7 qti](https://user-images.githubusercontent.com/14042373/43673485-6a422da8-97f6-11e8-8b75-10670c83e9bc.png)

**Comment by MEEllis** [comment]
![h k ysgc gi i9lc4k v](https://user-images.githubusercontent.com/14042373/43673555-98d29936-97f7-11e8-84f7-5b6366aed7ec.png)
  我把webpack.mock.js 移动位置， 一切都好了。

**Comment by jaywcjlove** [comment]
@MEEllis 因为新的版本为了监听文件变化，必须放到一个目录中，默认入口 `mocker/index.js` 放到目录中。

**Comment by MEEllis** [comment]
![10m1wfs6r eh307 dr im](https://user-images.githubusercontent.com/14042373/43937025-fc69878a-9c8d-11e8-8746-0eb66534510d.png)， 不太清楚你这个为啥 import 报错。

**Comment by MEEllis** [comment]
@jaywcjlove  我这里换成你案例中的require ，没有报这个错误了 ， **有些稀里糊涂的感觉**

**Comment by jaywcjlove** [comment]
@MEEllis Node.js 里面我一直使用 `require`  没有使用 `import` 的习惯。

**Comment by MEEllis** [comment]
okay...

**Comment by jaywcjlove** [comment]
@IEfucker 引用数据没有嘞，不知道你 `mocker/index.js` 里面怎么写的

**Comment by IEfucker** [comment]
idnex.js

```
const release = require('./article.mock')
const manage = require('./manage.mock')
const home = require('./home.mock')
const pic = require('./pic.mock')
const user = require('./user.mock')

const proxy = {
  ...release,
  ...manage,
  ...home,
  ...pic,
  ...user
}

module.exports = proxy
```

article.mock.js

```
const release = {
  [`POST ${BASE_URL}release`]: (req, res) => {
    console.log(`post ${BASE_URL}release`)
    return res.json(releaseRes)
  }
}

module.exports = release
```

**Comment by jaywcjlove** [comment]
@IEfucker 测试了一下没有什么问题，如果有问题新开 issue 讨论吧

https://github.com/jaywcjlove/webpack-api-mocker/blob/b587a3c30b125b979235e1564a126ccd6e63a521/example/express/mocker/user.mock.js#L1-L14

**Comment by IEfucker** [comment]
https://github.com/jaywcjlove/webpack-api-mocker/pull/8
之后我先研究下吧
