### ISSUE TITLE
安装指定版本报错

### ISSUE THREAD

**Issue by cuixi** [jaywcjlove/webpack-api-mocker#12]
想问下我直接npm安装的是1.4.2版本，指定1.4.3版本安装会报错是什么情况？

报错信息：

npm ERR! Darwin 17.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/lib/node_modules/cnpm/node_modules/.bin/npm" "--userconfig=/Users/Tracy/.nenpmrc" "--disturl=https://npm.taobao.org/mirrors/node" "--registry=http://rnpm.hz.netease.com/" "--cache=/Users/Tracy/.nenpm/.cache" "install"
npm ERR! node v9.2.1
npm ERR! npm  v3.10.10
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: webpack-api-mocker@^1.4.3
npm ERR! notarget Valid install targets:
npm ERR! notarget 1.4.2, 1.4.0
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'st-leave-message'

**Comment by jaywcjlove** [comment]
小版本更新  `sudo npm update webpack-api-mocker`

卸载再安装更新： `sudo npm uninstall webpack-api-mocker --save-dev`

安装 `sudo npm install webpack-api-mocker --save-dev`

指定版本安装，要先卸载吧

指定安装 `sudo npm install webpack-api-mocker@1.4.3 --save-dev`

@cuixi
