### ISSUE TITLE
mock的自定义函数中的req获取不到body

### ISSUE THREAD

**Issue by 6gunner** [jaywcjlove/webpack-api-mocker#14]
webpack配置：
`before(app) {`
      `apiMocker(app, path.resolve('./mock/index.js'), {`
        `changeHost: true,`
      `})`
`}`
mock/index.js文件
`'POST /ajax/getCustomerDetailInfo.json': (req, res) => {`
    `const {cust_no} = req.body;`
    `console.log(req.body, req.params, req.query);`
`})`
无论是post测试还是实际代码测试：
<img width="757" alt="wx20180807-150738 2x" src="https://user-images.githubusercontent.com/7445659/43760096-b57c302a-9a53-11e8-9d03-844d4d666fa2.png">

结果都是：
{} {} {}

**Comment by jaywcjlove** [comment]
![image](https://user-images.githubusercontent.com/1680273/43760874-f48b0de8-9a55-11e8-9fb2-58f67bdb3dad.png)

**Comment by zhangzqiang** [comment]
不明白为什么不在源码的index.js中

`
      if (contentType === 'text/plain') {
        bodyParserMethd = bodyParser.raw({ type: 'text/plain' });
      }
`

下面添加这段代码，亲测可用

`
      if (contentType.indexOf('x-www-form-urlencoded') > -1) { 
        bodyParserMethd = bodyParser.urlencoded({ extended: false });
      }
`

**Comment by jaywcjlove** [comment]
```bash
npm i webpack-api-mocker@1.5.9
```

@zhangzqiang 已更新

**Comment by IEfucker** [comment]
@1.5.15 还是获取不到body

**Comment by jaywcjlove** [comment]
@IEfucker 看请求头，示例中均可以获取，

不知道你是怎么请求的。

**Comment by callmegaga** [comment]
意思是不支持Content-Type: application/x-www-form-urlencoded是吧？
