### ISSUE TITLE
Delay

### ISSUE THREAD

**Issue by MEEllis** [jaywcjlove/webpack-api-mocker#17]
如何加入延时返回呢？类似于这种东西
![rrj oipwbfsc8mu 2 l0 94](https://user-images.githubusercontent.com/14042373/44501730-05bd6f80-a6c1-11e8-8266-b34810806944.png)

**Comment by jaywcjlove** [comment]
@MEEllis 给你提供了一个一模一样的延迟加载方法，请更新 [webpack-api-mocker@1.5.12+](https://www.npmjs.com/package/webpack-api-mocker/v/1.5.12)

```js
const delay = require('webpack-api-mocker/utils/delay');
const noProxy = process.env.NO_PROXY === 'true';

const proxy = {
  'GET /api/user': {
    id: 1,
    username: 'kenny',
    sex: 6
  },
  // ...
}
module.exports = (noProxy ? {} : delay(proxy, 1000));
```
