### ISSUE TITLE
Params are not able to contain any hyphens in the string

### ISSUE THREAD

**Issue by jphuangjr** [jaywcjlove/webpack-api-mocker#26]
Currently the params are not allowed to have any hyphens 

Example:
If we set the mock endpoint to be `GET /api/:userId`, and we hit it with a GET request to `/api/2342a-234ab-342`, it returns a 404. Otherwise if we make a GET request to  `/api/2342a234ab342`, the call succeeds.

**Comment by jaywcjlove** [comment]
@jphuangjr Fixed this issue, do you try to update the @v1.5.16 ?

**Comment by jphuangjr** [comment]
Great it works! Thanks!
