### ISSUE TITLE
cleanCache在apiMocker(app, path.resolve(__dirname, '../src/mock/index'))情况下不生效

### ISSUE THREAD

**Issue by wuzhixian1016** [jaywcjlove/webpack-api-mocker#30]
require.cache里的是以文件真实路径为索引的，所以当配置为：
`apiMocker(app, path.resolve(__dirname, '../src/mock/index'))`
或其他require也能识别的路径时，保存其他文件，入口文件缓存不会被清除，故导致没有更新。
版本1.5.11

**Comment by jaywcjlove** [comment]
你可以尝试更新到 `v1.6.1` 版本试一下

**Comment by wuzhixian1016** [comment]
还是一样的，因为require会自动补全文件路径，但是你代码里面并没有这个操作，所以两个路径就不相同了，所以就没有清除到缓存。
其实只要配置写全就没问题了，这里只是提一下有这个坑哈，或者你代码里面也可以判断一下然后做下兼容？

**Comment by jaywcjlove** [comment]
@wuzhixian1016 

有没有后缀 `.js` 不一致 导致不能监听，实时更新Mock文件？

```js
path.resolve(__dirname, '../src/mock/index')
```

**Comment by jaywcjlove** [comment]
@wuzhixian1016 

经过测试么有你所述 问题，是 `Windows` 平台？将路径拼错了？

**Comment by wuzhixian1016** [comment]
```
 // 释放老模块的资源`
  function cleanCache(modulePath) {
   // 这里require.cache存的索引是require补全后的路径，如果我们配置的是没有.js后缀的路径就匹配不到了
    var module = require.cache[modulePath];
  // 所以这里缓存没有被清除
    if (!module) return;
    // remove reference in module.parent
    if (module.parent) {
      module.parent.children.splice(module.parent.children.indexOf(module), 1);
    }
    require.cache[modulePath] = null;
  }
```

**Comment by jaywcjlove** [comment]
@wuzhixian1016 

发布了 `webpack-api-mocker@1.6.2` 版本，你是否有效解决问题。

**Comment by wuzhixian1016** [comment]
我倒是没什么问题哈，只要把后缀加上就好，只是研究一下这个bug，但是根据common规范我还可以这么写哈哈哈：
`apiMocker(app, path.resolve('./mocker'))`
require也是可以解析到index.js

**Comment by wuzhixian1016** [comment]
看了下文档，发现可以用
`require.resolve(watchFile)`
先解析一下路径

**Comment by jaywcjlove** [comment]
@wuzhixian1016 这个样子更完美，我去更新一下文档。

thx!

**Comment by wuzhixian1016** [comment]
很高兴可以帮忙，不过`require.resolve(watchFile)`不是应该加在源码里面吗？？！

**Comment by jaywcjlove** [comment]
@wuzhixian1016 提交了 😄
