### ISSUE TITLE
mocker下有多个文件时，无法热更新

### ISSUE THREAD

**Issue by SoyMeng** [jaywcjlove/webpack-api-mocker#4]
mocker下有多个文件时，无法热更新

**Comment by jaywcjlove** [comment]
默认热更指定的 JS 文件，还没有找到方法监听，这个指定的 `JS` 引用的其它 JS 文件。

**Comment by SoyMeng** [comment]
最好的方式应该是监听整个文件夹吧，index通过另外的参数指定

**Comment by jaywcjlove** [comment]
@SoyMeng 监听整个文件夹去 热更新，也需要研究一下怎么去实现。

**Comment by SoyMeng** [comment]
嗯，我也试试

**Comment by XiongAmao** [comment]
我尝试做了一个监听配置文件入口所在的目录来热更新文件的功能 #8

**Comment by jaywcjlove** [comment]
@SoyMeng @XiongAmao 已发版

`webpack-api-mocker@1.5.5`
