### ISSUE TITLE
proxy did not work

### ISSUE THREAD

**Issue by slink1811** [jaywcjlove/webpack-api-mocker#5]
We use webpack-api-mocker for mocking our endpoint, but now want to implement one, so we tried this:
```js
apiMocker(app, path.resolve('config/mocker.js'), {
  proxy: {
    '/ml/customer//*': 'http://localhost:8086/'
  },
  changeHost: true
})
```
like in the readme and example. But it never fetches from :8068 but still from mocker.js. Sorry if it isn't an issue but my misconfiguration.

Best, Sven

**Comment by jaywcjlove** [comment]
@slink1811 Here is an example:

https://github.com/jaywcjlove/webpack-api-mocker/blob/master/example/webpack.config.js#L17-L22

**Comment by codepandy** [comment]
@jaywcjlove my proxy also didn't work,the below is my code:
```
   apiMocker(app, path.resolve("./mocker/index.js"), {
        proxy: {
          "/remote/*": "https://www.baidu.com/",
          "/api/*": `http://localhost:3000`
        },
        changeHost: true
      });
```

```
"start:no-mock": "NO_PROXY=true node scripts/start.js",
```

my project created by the `create-react-app` .

**Comment by jaywcjlove** [comment]
@codepandy 


https://github.com/jaywcjlove/mocker-api/blob/d86465ef299f92dcbb76d01ef62fd1620e8d32ab/example/base/package.json#L6-L8

Example: 

https://github.com/jaywcjlove/mocker-api/tree/5287a4c4707988c810af57cf7a7b22fe74aad42a

**Comment by codepandy** [comment]
@jaywcjlove 
I installed the package, and I started a mocker server.
but the proxy don't work, the http request can't be transfer the target.

**Comment by jaywcjlove** [comment]
![image](https://user-images.githubusercontent.com/1680273/58246465-b60fef80-7d89-11e9-8226-2ec99861856b.png)

The test found no problems. I don't know what errors you have.

**Comment by codepandy** [comment]
your demo is the mocker server, my question is the proxy config. the mocker is ok.

**Comment by codepandy** [comment]
the below is my project, could you run it?
https://github.com/codepandy/react_pwa

**Comment by jaywcjlove** [comment]
@codepandy 是的

**Comment by codepandy** [comment]
@jaywcjlove
那个代理是不是没作用啊，设置代理，都代理不过去，请求的还是本地的mock，不走代理的服务。

**Comment by freezer-glp** [comment]
> @jaywcjlove
> 那个代理是不是没作用啊，设置代理，都代理不过去，请求的还是本地的mock，不走代理的服务。

Hi, Please remove the local mock, just config the ` proxy: { ... }`. And try again. This works for me.

你好，试试删除本地mock配置，只留 `proxy:{..}`的配置。我这样就可以实现请求转发了，否则优先走本地mock配置。
