### ISSUE TITLE
fs.watch问题

### ISSUE THREAD

**Issue by luobin01** [jaywcjlove/webpack-api-mocker#6]
问题：在mac pro上运行，发现fs.watch无法实时监听mock.js文件的变化
解决：将fs.watch改为fs.watchFile，再加参数{ interval: 1000 }。

**Comment by jaywcjlove** [comment]
@luobin01 

`webpack-api-mocker@1.5.2`

官方文档说：

> 注意：fs.watch() 比 fs.watchFile 和 fs.unwatchFile 更高效。 可能的话，应该使用 fs.watch 而不是 fs.watchFile 和 fs.unwatchFile。
